name: baitaplon
description: "A new Flutter project for Klever Fruits."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0

  # Thư viện kết nối API
  http: ^1.1.0

  # Thư viện lưu trữ dữ liệu (giỏ hàng, đăng nhập)
  shared_preferences: ^2.2.2

  # Thư viện định dạng tiền tệ và ngày tháng (ĐÃ THÊM Ở ĐÂY)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Quản lý hình ảnh logo của dự án Klever Fruits
assets:
  - assets/images/
